### ISSUE TITLE
IOMUX details

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/polarfire-soc-bare-metal-examples#1]
In every driver the following statement is given:

**For more information on IOMUX, refer to the IOMUX section of the PolarFire SoC Microprocessor Subsystem (MSS) User's Guide.**

I cannot find any document containing Pin multiplexing details such as register settings etc. Please pin point me to the relevant information.

**Comment by nitindeshpande** [comment]
Hello,
 Please refer to the [PolarFire Device Register Map](https://www.microsemi.com/document-portal/doc_download/1243471-polarfire-device-register-map) for the register details.
 
Look for IOMUX in PFSOC_MSS_TOP_SYSREG section.

We will have the name of the document corrected in the .h files.

**Comment by kowalski100** [comment]
I couldn't find IOMUX section in your mentioned Excel sheet ([PolarFire Device Register Map](https://www.microsemi.com/document-portal/doc_download/1243471-polarfire-device-register-map)), please.

**Comment by nitindeshpande** [comment]
Apologies, Please refer to the [PolarFire SoC Register Map](https://www.microsemi.com/document-portal/doc_download/1244581-polarfire-soc-register-map)

**Comment by kowalski100** [comment]
I guess these setting contains settings like:

=> 0: Connect Peripheral to MSS
=> 1: Connect Peripheral to Fabric
**Please correct me if I am wrong?**

_The thing I was looking for is: How to configure/connect a physical pin to a certain peripheral? i.e **PIN multiplexing.**_

![Capture](https://user-images.githubusercontent.com/7781522/127122675-596ef27a-c4c5-4fb4-84ea-6b14f0f07a99.PNG)

**Comment by nitindeshpande** [comment]
Hi,
Please refer to the [MSS Configurator User Guide] (https://www.microsemi.com/document-portal/doc_download/1245690-polarfire-soc-standalone-mss-configurator-user-guide-for-v2021-1) to know how the mapping is done using configurator.

You may also refer to section 6.9 in the [PolarFire® SoC MSS Technical Reference Manual](https://internal.onlinedocs.microchip.com/pr/GUID-0E320577-28E6-4365-9BB8-9E1416A0A6E4-en-US-1/index.html)

**Comment by nitindeshpande** [comment]
Hi kowalski100,
 Did you find the info you were looking for?

**Comment by kowalski100** [comment]
Yes. Thank you.
