### ISSUE TITLE
Icicle Schematics doesn't match with i2c instructions

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/polarfire-soc-bare-metal-examples#2]
I need to test I2c interface. 

The instruction about J26 [here ](https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/tree/main/driver-examples/mss-i2c/mpfs-i2c-master-slave)doesn't match schematic [here](https://www.microsemi.com/document-portal/doc_download/1245126-polarfire-soc-icicle-kit-schematics).

One more thing, I couldn't find any document containing default PIN state (which peripheral by default that appears on a pin)?

**Comment by nitindeshpande** [comment]
@kowalski100 
The instructions in the readme look correct. (There's a formatting issue that needs to be sorted, will do that. Please look at the raw file for now.)

| I2C-0       |      I2C-1 |
| ---------- | --------- |
| I2C 0 SCL: J26 Pin 29  -> |  I2C 1 SCL: J26 Pin 31 |
| I2C 0 SDA: J26 Pin 35 -> | I2C 1 SDA: J26 Pin 37 |

Note also that, as mentioned in the project readme, the I2C_LOOPBACK variant of the [reference design](https://github.com/polarfire-soc/icicle-kit-reference-design) needs to be used for this (The default reference design does not have this connection). 

I am not sure what you mean when you say that the readme instructions dont match the schematics.

**Comment by kowalski100** [comment]
@nitindeshpande 
Thank for your kind reply.

I mean I cannot see any I2C signals on J26 as can be seen from the attachment below.

![j26](https://user-images.githubusercontent.com/7781522/129155010-d870deef-db8a-4ea8-ab19-b20ed6886b40.PNG)

**Comment by nitindeshpande** [comment]
Ok. Yes, The I2C loopback design variant routes the I2C signals to the J26.

**Comment by nitindeshpande** [comment]
Hello @kowalski100
Hope your question was answered. Can the issue be closed?

**Comment by nitindeshpande** [comment]
Believe the query is answered.
