### ISSUE TITLE
applications/mpfs-pmp-demo/README.md: The link to demo document mpfs-pmp-demo.md is broken

### ISSUE THREAD

**Issue by kevinscully100** [polarfire-soc/polarfire-soc-bare-metal-examples#3]
The link to the demo document "mpfs-pmp-demo.md" is broken in [/applications/mpfs-pmp-demo/README.md](https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/blob/main/applications/mpfs-pmp-demo/README.md)

The link to the demo document "mpfs-pmp-demo.md" should be: 
https://github.com/polarfire-soc/polarfire-soc-documentation/blob/master/demo-guides/mpfs-pmp-demo.md

**Comment by nitindeshpande** [comment]
This is resolved. Will be  available soon.

**Comment by nitindeshpande** [comment]
Resolved with 2021.11
