### ISSUE TITLE
Fabric-IP Examples

### ISSUE THREAD

**Issue by bkzshabbaz** [polarfire-soc/polarfire-soc-bare-metal-examples#8]
Are there plans to release example code to talk to IP cores in the fabric?  I see there is a placeholder for a CoreGPIO block, but it's empty.  I'm currently struggling to talk to a CoreGPIO and CoreTimer block in the fabric.  Any memory mapped I/O interactions result in no action from the IP.
I'm not sure if I'm missing something during initialization.  I've already made the following calls:
`    (void) mss_config_clk_rst(MSS_PERIPH_FIC3, (uint8_t) 0, PERIPHERAL_ON);
    (void) mss_config_clk_rst(MSS_PERIPH_CFM, (uint8_t) 0, PERIPHERAL_ON);
`

**Comment by hughbreslin** [comment]
Hey @bkzshabbaz sorry for the delay in spotting this! 

Yes it sounds like this is related, could you try enabling the FPGA reset that was described in this [issue](https://github.com/polarfire-soc/icicle-kit-reference-design/issues/13) and see if it resolves things for you? :)

**Comment by bkzshabbaz** [comment]
Indeed, it did resolve it.  I'll be on the lookout for the other issue to be resolved and then migrate our code.
